name: Publish Libraries

on:
  pull_request:
    types: [ closed ]
    branches: [ master ]

jobs:
  publish:
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.TOKEN }}
          submodules: true
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_REPOSITORY: ${{ github.repository }}

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build extension library
        run: ./gradlew :extension:assembleRelease

      - name: Publish extension library
        run: ./gradlew :extension:publishReleasePublicationToGitHubPackagesRepository

      - name: Build UI library
        run: ./gradlew :ui:assembleRelease

      - name: Publish UI library
        run: ./gradlew :ui:publishReleasePublicationToGitHubPackagesRepository